apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: app
spec:
  storageClassName: local-storage-db
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db
    type: ""
  claimRef:
    name: mongodb-pvc
    namespace: app
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem