apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: app
  labels:
    db: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongodb
  template:
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - name: mongodb-deployment
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-pv
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 5
      volumes:
        - name: mongodb-pv
          persistentVolumeClaim:
            claimName: mongodb-pvc
      restartPolicy: Always