apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-db
value: 2000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class should be used for mongodb service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-backend
value: 2000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class should be used for backend service pods only."